[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'
hook_add = 'source ~/.config/nvim/plugins/denite.rc.vim'

# 非同期で実行
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# Color scheme
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add='source ~/.config/nvim/plugins/iceberg.rc.vim'

# ファイルツリー
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add='source ~/.config/nvim/plugins/nerdtree.rc.vim'

# fuzzy finder
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

# fzf for vim
[[plugins]]
repo = 'junegunn/fzf.vim'
if = 'executable("fzf")'
depends = 'junegunn/fzf'
hook_add = 'source ~/.config/nvim/plugins/fzf-vim.rc.vim'

# Git
[[plugins]]
repo = "tpope/vim-fugitive"
hook_add = 'source ~/.config/nvim/plugins/vim-fugitive.rc.vim'

# Asynchronous syntax checker
[[plugins]]
repo = 'w0rp/ale'
on_ft = ['ruby', 'javascript', 'javascript.jsx', 'typescript']
hook_add = 'source ~/.config/nvim/plugins/ale.rc.vim'

# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/plugins/lightline.rc.vim'
on_source = ['vim-fugitive', 'ale']
