[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'
hook_add = 'source ~/.config/nvim/plugins/denite.rc.vim'

# 非同期で実行
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# Color scheme
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add='source ~/.config/nvim/plugins/iceberg.rc.vim'

# ファイルツリー
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add='source ~/.config/nvim/plugins/nerdtree.rc.vim'
