# js syntax highlighter
[[plugins]]
repo = 'billyvg/tigris.nvim'
on_ft = ['javascript', 'javascript.jsx']
hook_post_update = 'source ~/.config/nvim/plugins/tigris.rc.vim'

# TypeScript
[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = 'typescript'
depends = ['vimproc']
hook_add = 'call local#dein#lang#typescript#hook_add_tsuquyomi()'

[[plugins]]
repo = 'mhartington/nvim-typescript'
on_ft = ['typescript']
build = './install.sh'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft  = 'typescript'

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['typescript', 'javascript']

# toml syntax highlighter
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
