# js syntax highlighter
[[plugins]]
repo = 'billyvg/tigris.nvim'
on_ft = ['javascript', 'javascript.jsx']
hook_post_update = 'source ~/.config/nvim/plugins/tigris.rc.vim'

# JavaScript indent
[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'javascript.jsx', 'typescript']

# TypeScript
[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = 'typescript'

# TypeScript syntax highlighter
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

# toml syntax highlighter
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# indent
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'source ~/.config/nvim/plugins/indentLine.rc.vim'

# カッコ補完
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# ホワイトスペースを可視化
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
