[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'
hook_add = 'source ~/.config/nvim/plugins/denite.rc.vim'
hook_source = '''
call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])

call denite#custom#source('file_rec', 'matchers', ['matcher_fuzzy','matcher_ignore_globs'])
call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
      \ [
      \ '.git/',
      \ 'build/',
      \ '__pycache__/',
      \ 'images/',
      \ '*.o',
      \ '*.make',
      \ '*.min.*',
      \ 'img/',
      \ 'fonts/',
      \ 'bin/',
      \ 'node_modules/',
      \ 'public/uploads/',
      \ 'tmp/'])
'''

# filetype checker
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['javascript', 'javascript.jsx', 'html', 'html.eruby', 'vue']
on_i = 1
hook_add = '''
let g:user_emmet_leader_key = ','
'''

# html
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

# js syntax highlighter
[[plugins]]
repo = 'billyvg/tigris.nvim'
on_ft = ['javascript', 'javascript.jsx']
hook_post_update = 'source ~/.config/nvim/plugins/tigris.rc.vim'

# JavaScript indent
[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'javascript.jsx', 'typescript']

# TypeScript
[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = 'typescript'

# TypeScript syntax highlighter
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

# Slim syntax highlighter
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

# toml syntax highlighter
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# indent
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'source ~/.config/nvim/plugins/indentLine.rc.vim'

# カッコ補完
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# ホワイトスペースを可視化
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# 非同期での補完フレームワーク
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
build = ':UpdateRemotePlugins'
hook_source = 'source ~/.config/nvim/plugins/deoplete.rc.vim'

# スニペット
[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_source = 'source ~/.config/nvim/plugins/neosnippet.rc.vim'

# JavaScript補完
[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript', 'javascript.jsx']
build = 'npm install -g tern'
depends = ['deoplete.nvim']

# jsx synta highlighter
[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'javascript.jsx']
